# Generated by Django 3.0.6 on 2020-05-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evento_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
